version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0

jobs:
    setup:
      docker:
        - image: cimg/ruby:2.7-node
      steps:
        - checkout
        - ruby/install-deps
    test:
      docker:
        - image: cimg/ruby:2.7-node
      steps:
        - checkout
        - ruby/install-deps
        # Run rspec
        - ruby/rspec-test
      
workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup